import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en-US': english,
        'hi-IN': hindi,
        'ml-IN': malayalam,
      };

  /// English

  Map<String, String> english = {
    'greeting': 'Hello',
    "TSQ": "Are you a student or an instructor at this institution?",
    "Student": "Student",
    "Teacher": "Teacher",
    "english": "English",
    "hindi": "Hindi",
    "malayalam": "Malayalam",
    "langQ": "Your Preferred language",
    "submit": "Submit",
    "Name": "Name",
    "Password": "Password",
    "Age": "Age",
    "Class": "Class",
    "Address": "Address",
    "FathersName": 'Father\'s Name',
    "MothersName": "Mother's Name",
    "Experience": "Experience",
    "classList": "Select classes you teach",
    "edit": "Edit",
    "classTQ": "Are you a class teacher?",
    "Yes": "Yes",
    "No": "No",
    "RollNo": "Roll No",
    "Profile": "Profile",
    "Home": "Home",
    "Present": "Present",
    "Absent": "Absent",
    "TotalChildren": "Total Children",
    "Attendance": "Attendance",
    "Assignments": "Assignments",
    "Schedule": "Schedule",
    "duration": "Duration",
    "time": "Time",
    "tutor/event": "Tutor/Event",
    "class/event":"Class/Event",
    "currentSession": "Current Session",
    "msgSession": "No ongoing session at the moment!",
    "submittedAssignments": "Submitted Assignments",
    "addAssignments": 'Add Assignments',
    "msgEditButtonClick": "Click edit button first",
    "registerSuccess": "Registration success",
    "msgRegWarning": "Fields and image must not be empty!",
    "emptyWarning": "Field must be not empty!",
    "loginErrorWaring": "Incorrect Username or Password",
    "updateSuccess": "Data updated successfully",
    "addImageWaring": "Add Image to list",
    "loginSuccess": "Successfully logged in",
    "imageClick": "Click to add image",
    "noData": "No data available",
    "newPassword": "New password",
    "reEnterPassword": "Re enter password",
    "passwordsNotMatch":
        "The passwords entered do not match. Please try again.",
    "passwordChangedSuccess": "Password changed successfully",
    "settings": "Settings",
    "classWarning":
        "Choose classes 1 - 4 in this school which has only LP section",
    "nameWarning": "Entering valid name number is not allowed",
    "rollNoWarning":
        "Please enter your roll number accurately as each class has fifty pupils",
    "ageWarning": "Please enter a valid age",
    "expWarning": "Please enter a valid experience",
    "logoutWarning": "Are you sure you want to logout?",
    "yes": "Yes",
    "cancel": "Cancel",
    "warning": "Warning",
    "logout": "Logout",
    "validateWarning": "Form validation went wrong, correct form details",
    "forgotPassword": "Forgot Password",
    "signUp": "Sign Up",
    "signUpMessage": "Don't you have an account?",
    "login": "Login",
    "userNotExist":"User does not exist",
    "userNameNotEmpty":"Username must not be empty",
    "or":"Or",
    "signIn":"Sign In",
    "havingAnAccount":"You already have an account?",
    "attendanceWarning":"You are selecting a future date for attendance. Are you sure?",
    "userExist" :"Username already exist",
    "student":"Student",
    "teacher":"Teacher",
    "your":"Your",
    "allTeacher":"All teachers"

  };

  /// Hindi

  Map<String, String> hindi = {
    "Name": "नाम",
    "Password": "पासवर्ड",
    "Age": "आयु",
    "Class": "कक्षा",
    "Address": "पता",
    "FathersName": 'पिता का नाम',
    "MothersName": "मां का नाम",
    "Experience": "अनुभव",
    'greeting': 'नमस्ते',
    "TSQ": "क्या आप इस संस्थान के छात्र या अध्यापक हैं?",
    "Student": "छात्र",
    "Teacher": "अध्यापक",
    "hindi": "हिंदी",
    "malayalam": "मलयालम",
    "english": "इंग्लिश",
    "langQ": "आपकी पसंदीदा भाषा",
    "submit": "जमा करना",
    "classList": "वे कक्षाएँ चुनें जिन्हें आप पढ़ाते हैं",
    "edit": "संपादन करना",
    "classTQ": "क्या आप क्लास टीचर हैं?",
    "Yes": "हाँ",
    "No": "नहीं",
    "RollNo": "रोल नंबर",
    "Profile": "प्रोफ़ाइल",
    "Home": "मुख्य पृष्ठ",
    "Present": "जो आये",
    "Absent": "जो नहीं आते",
    "TotalChildren": "कुल बच्चे",
    "Attendance": "उपस्थिति",
    "Assignments": "छात्रों के कार्य",
    "Schedule": "अनुसूची",
    "duration": "अवधि",
    "time": "समय",
    "tutor/event": "शिक्षक/घटना",
    "class/event": "कक्षा/घटना",
    "currentSession": "वर्तमान सत्र",
    "msgSession": "फिलहाल कोई सत्र नहीं चल रहा है!",
    "submittedAssignments": "सबमिट किए गए असाइनमेंट",
    "addAssignments": 'असाइनमेंट जोड़ें',
    "msgEditButtonClick": "सबसे पहले एडिट बटन पर क्लिक करें",
    "registerSuccess": "पंजीकरण सफलता",
    "msgRegWarning": "फ़ील्ड और छवि खाली नहीं होनी चाहिए!",
    "emptyWarning": "फ़ील्ड खाली नहीं होनी चाहिए!",
    "loginErrorWaring": "गलत उपयोगकर्ता नाम या पासवर्ड",
    "updateSuccess": "डेटा सफलतापूर्वक अपडेट किया गया",
    "addImageWaring": "सूची में छवि जोड़ें",
    "loginSuccess": "सफलतापूर्वक लॉग इन किया गया",
    "imageClick": "छवि जोड़ने के लिए क्लिक करें",
    "noData": "कोई डेटा मौजूद नहीं",
    "newPassword": "नया पासवर्ड",
    "reEnterPassword": "पासवर्ड फिर से दर्ज करें",
    "passwordsNotMatch":
        "दर्ज किए गए पासवर्ड मेल नहीं खाते. कृपया पुन: प्रयास करें।",
    "passwordChangedSuccess": "पासवर्ड सफलतापूर्वक बदला गया",
    "settings": "समायोजन",
    "classWarning": "इस स्कूल में कक्षा 1 - 4 चुनें जिसमें केवल एलपी अनुभाग हो",
    "nameWarning": "वैध नाम संख्या दर्ज करने की अनुमति नहीं है",
    "rollNoWarning":
        "कृपया अपना रोल नंबर सही दर्ज करें क्योंकि प्रत्येक कक्षा में पचास छात्र हैं",
    "ageWarning": "कृपया वैध आयु दर्ज करें",
    "expWarning": "कृपया एक वैध अनुभव दर्ज करें",
    "logoutWarning": "क्या आप लॉग आउट करना चाहते हैं?",
    "yes": "हाँ",
    "cancel": "रद्द करना",
    "warning": "चेतावनी",
    "logout": "लॉग आउट",
    "validateWarning": "फॉर्म सत्यापन गलत हो गया, फॉर्म विवरण सही करें",
    "forgotPassword": "पासवर्ड भूल गए",
    "signUp": "साइन अप करें",
    "signUpMessage": "क्या आपके पास कोई खाता नहीं है?",
    "login": "लॉग इन करें",
    "userNotExist":"उपभोगकर्ता मौजूद नहीं",
    "userNameNotEmpty":"उपयोक्तानाम खाली नहीं होना चाहिए",
    "or":"या",
    "signIn":"दाखिल करना",
    "havingAnAccount":"आपका पहले से ही खाता है?",
    "attendanceWarning":"आप उपस्थिति के लिए भविष्य की तारीख का चयन कर रहे हैं। क्या आपको यकीन है?",
     "userExist" :"उपयोगकर्ता नाम पहले से मौजूद",
    "student":"विद्यार्थी",
    "teacher":"अध्यापक",
    "your":"आपका",
    "allTeacher":"सब गुरू"
  };

  /// Malayalam

  Map<String, String> malayalam = {
    "Name": "പേര്",
    "Password": "പാസ്‌വേഡ്",
    "Age": "പ്രായം",
    "Class": "ക്ലാസ്",
    "Address": "വിലാസം",
    "FathersName": 'അച്ഛൻ്റെ പേര്',
    "MothersName": "അമ്മയുടെ പേര്",
    "Experience": "എക്സ്പീരിയൻസ്",
    "classList": "നിങ്ങൾ പഠിപ്പിക്കുന്ന ക്ലാസ്സുകൾ തിരഞ്ഞെടുക്കുക",
    'greeting': 'നമസ്കാരം',
    "Teacher": "അധ്യാപകൻ",
    "Student": "വിദ്യാർത്ഥി",
    "malayalam": "മലയാളം",
    "english": "ഇംഗ്ലീഷ്",
    "hindi": "ഹിന്ദി",
    "langQ": "നിങ്ങൾക്ക് ഇഷ്ടപ്പെട്ട ഭാഷ",
    "TSQ": "നിങ്ങൾ ഈ വിദ്യാലയത്തിലെ അധ്യപകനാണോ അതോ വിദ്യാർത്ഥി ആണോ?",
    "submit": "സമർപ്പിക്കുക",
    "edit": "തിരുത്തുക",
    "classTQ": "നിങ്ങൾ ഒരു ക്ലാസ് ടീച്ചർ ആണോ?",
    "Yes": "അതെ",
    "No": "ഇല്ല",
    "RollNo": "റോൾ നമ്പർ",
    "Profile": "പ്രൊഫൈൽ",
    "Home": "പ്രധാന പേജ്",
    "Present": "വന്നവർ",
    "Absent": "വരാത്തവർ",
    "TotalChildren": "ആകെ കുട്ടികൾ",
    "Attendance": "ഹാജർ",
    "Assignments": "അസൈൻമെന്റ്",
    "Schedule": "ഷെഡ്യൂൾ ",
    "duration": "ദൈർഘ്യം",
    "time": "സമയം",
    "tutor/event": "ട്യൂട്ടർ/ഇവന്റ്",
    "class/event":"ക്ലാസ്/ഇവന്റ്",
    "currentSession": "നിലവിലെ സെഷൻ",
    "msgSession": "ഇപ്പോൾ സെഷൻ നടക്കുന്നില്ല!",
    "submittedAssignments": "സമർപ്പിച്ച അസൈൻമെന്റുകൾ",
    "addAssignments": 'അസൈൻമെന്റ് ചേർക്കുക',
    "msgEditButtonClick": "ആദ്യം എഡിറ്റ് ബട്ടൺ ക്ലിക്ക് ചെയ്യുക",
    "registerSuccess": "രജിസ്ട്രേഷൻ വിജയം",
    "msgRegWarning": "ഫീൽഡുകളും ചിത്രവും ശൂന്യമായിരിക്കരുത്!",
    "emptyWarning": "ഫീൽഡ് ശൂന്യമായിരിക്കരുത്!",
    "loginErrorWaring": "തെറ്റായ ഉപയോക്തൃ നാമം അല്ലെങ്കിൽ പാസ്വേഡ്",
    "updateSuccess": "ഡാറ്റ വിജയകരമായി അപ്ഡേറ്റ് ചെയ്തു",
    "addImageWaring": "പട്ടികയിലേക്ക് ചിത്രം ചേർക്കുക",
    "loginSuccess": "ലോഗിൻ ചെയ്തു",
    "imageClick": "ചിത്രം ചേർക്കാൻ ക്ലിക്ക് ചെയ്യുക",
    "noData": "ഡാറ്റ ലഭ്യമല്ല",
    "newPassword": "പുതിയ പാസ്വേഡ്",
    "reEnterPassword": "പാസ്വേഡ് വീണ്ടും നൽകുക",
    "passwordsNotMatch":
        "നൽകിയ പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    "passwordChangedSuccess": "പാസ്‌വേഡ് വിജയകരമായി മാറ്റി",
    "settings": "ക്രമീകരണങ്ങൾ",
    "classWarning":
        "എൽപി വിഭാഗം മാത്രമുള്ള ഈ സ്കൂളിൽ 1 - 4 ക്ലാസുകൾ തിരഞ്ഞെടുക്കുക",
    "nameWarning": "സാധുവായ പേര് നമ്പർ നൽകുന്നത് അനുവദനീയമല്ല",
    "rollNoWarning":
        "ഓരോ ക്ലാസിലും അമ്പത് കുട്ടികളുള്ളതിനാൽ നിങ്ങളുടെ റോൾ നമ്പർ കൃത്യമായി നൽകുക",
    "ageWarning": "ദയവായി ഒരു സാധുവായ പ്രായം നൽകുക",
    "expWarning": "സാധുവായ ഒരു അനുഭവം നൽകുക",
    "logoutWarning": "ലോഗ്ഔട്ട് ചെയ്യണമെന്ന് തീർച്ചയാണോ?",
    "yes": "അതെ",
    "cancel": "റദ്ദാക്കുക",
    "warning": "മുന്നറിയിപ്പ്",
    "logout": "പുറത്തുകടക്കുക",
    "validateWarning":
        "ഫോം മൂല്യനിർണ്ണയം തെറ്റായി പോയി, ശരിയായ ഫോം വിശദാംശങ്ങൾ",
    "forgotPassword": "പാസ്വേഡ് മറന്നോ",
    "signUp": "സൈൻ അപ്പ് ചെയ്യുക",
    "signUpMessage": "നിനക്ക് അക്കൗണ്ട് ഇല്ലേ?",
    "login": "ലോഗിൻ",
    "userNotExist":"ഉപയോക്താവ് നിലവിലില്ല",
    "userNameNotEmpty":"ഉപയോക്തൃനാമം ശൂന്യമായിരിക്കരുത്",
    "or":"അല്ലെങ്കിൽ",
    "signIn":"സൈൻ ഇൻ",
    "havingAnAccount":"നിങ്ങൾക്ക് ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ?",
    "attendanceWarning":"നിങ്ങൾ ഹാജരാകുന്നതിന് ഭാവി തീയതി തിരഞ്ഞെടുക്കുന്നു. നിങ്ങൾക്ക് ഉറപ്പാണോ?",
    "userExist" :"ഉപയോക്തൃനാമം ഇതിനകം നിലവിലുണ്ട്",
    "student":"വിദ്യാർത്ഥി",
    "teacher":"അധ്യാപകൻ",
    "your":"നിങ്ങളുടെ",
    "allTeacher":"എല്ലാ അധ്യാപകരും"

  };
}

